import re
expressions = {
    re.compile('(?i)(.*)(ventaana)(.*)') : 'ventana',
    re.compile('(?i)(.*)(revicion)(.*)') : 'revisión',
    re.compile('(?i)(.*)(rempllazo|remplazo|replazo)(.*)'): 'reemplazo',
    re.compile('(?i)(.*)(lampara|lapara)(.*)'): 'lámpara',
    re.compile('(?i)(.*)(decentrado)(.*)'): 'descentrado',
    re.compile('(?i)(.*)(vehiculo)(.*)'): 'vehículo',
    re.compile('(?i)(.*)(hidroneumatico)(.*)'): 'hidroneumático',
    re.compile('(?i)(.*)(plafon)((?:\s|$).*)'): 'plafón',
    re.compile('(?i)(.*)(deteriodo)(.*)'): 'deterioro',
    re.compile('(?i)(.*)(sub urbana)(.*)'): 'suburbana',
    re.compile('(?i)(.*)(energia)(.*)'): 'energía',
    re.compile('(?i)(.*)(ceramica)(.*)'): 'cerámica',
    re.compile('(?i)(.*)(labavo)(.*)'): 'lavabo',
    re.compile('(?i)(.*)(calenton)((?:\s|$).*)'): 'calentón',
    re.compile('(?i)(.*)(3d)(.*)'): '3D',
    re.compile('(?i)(.*)(balstro)(.*)'): 'balastro',
    re.compile('(?i)(.*)(hidraulic)([ao].*)') : 'hidráulic',
    re.compile('(?i)(.*)(porton)((?:\s|$).*)'): 'portón',
    re.compile('(?i)(.*)(cemeto)(.*)'): 'cemento',
    re.compile('(?i)(.*)(deprtamento)(.*)'): 'departamento',
    re.compile('(?i)(.*)(vvidrio)(.*)'): 'vidrio',
    re.compile('(?i)(.*)([ ]{2,})(.*)'): ' ',
    re.compile('(?i)(.*)([,]{2,})(.*)'): ',',
    re.compile('(?i)(.*)([.]{2,})(.*)'): ' ',
    re.compile('(?i)(.*)([ ]+,)(.*)'): ',',
    re.compile('(?i)(.*)(,[ ]{2,})(.*)'): ', ',
    re.compile('(?i)(.*\w+)(cion)((?:\s|$).*)'): 'ción',
    re.compile('(?i)(.*\w+)(sion)((?:\s|$).*)'): 'sión',
    re.compile('(?i)(.*)(plafoneria)(.*)'): 'plafonería',
    re.compile('(?i)(.*)(deseñaletica)(.*)'): 'de señalética',
    re.compile('(?i)(.*)(plafonenes)(.*)'): 'plafones',
    re.compile('(?i)(.*\w+)(ilico)(s?(?:\s|$).*)'): 'ílico',
    re.compile('(?i)(.*\w+)(istico)(s?(?:\s|$).*)'): 'ístico',
    re.compile('(?i)(.*)(istica)(s?(?:\s|$).*)'): 'ística',
    re.compile('(?i)(.*)(dia)(s?(?:\s|$).*)') : 'día',
    re.compile('(?i)(.*)(lamina)(s?(?:\s|$).*)') : 'lámina',

}
